### ISSUE TITLE
NoMethodError: undefined method `pretty_name_leader' for #<Hackbot::Conversations::SetPoc:0x007fefe5444288>

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/api#112]
https://sentry.io/hack-club/api/issues/231266910/

```
NoMethodError: undefined method `pretty_name_leader' for #<Hackbot::Conversations::SetPoc:0x007fefe5444288>
Did you mean?  pretty_leader_name
  app/models/hackbot/conversations/set_poc.rb:111:in `associate_one_in_many_clubs'
    leader_name: pretty_name_leader(leader))
  app/models/hackbot/conversations/set_poc.rb:60:in `associate_clubs'
    associate_one_in_many_clubs clubs, leader
  app/models/hackbot/conversations/set_poc.rb:18:in `start'
    associate_clubs(leader.clubs, leader)
  app/models/hackbot/conversation.rb:28:in `handle'
    next_state = send(state, event)
  app/models/hackbot/conversations/channel.rb:12:in `handle'
    super
...
(144 additional frame(s) were not displayed)

NoMethodError: undefined method `pretty_name_leader' for #<Hackbot::Conversations::SetPoc:0x007fefe5444288>
Did you mean?  pretty_leader_name
```

**Comment by paked** [comment]
Fixed.
