### ISSUE TITLE
TypeError: no implicit conversion of Symbol into Integer

### ISSUE THREAD

**Issue by paked** [hackclub/api#122]
https://sentry.io/hack-club/api/issues/231177261/

```
TypeError: no implicit conversion of Symbol into Integer
  lib/giphy_client.rb:16:in `[]'
    JSON.parse(resp, symbolize_names: true)[:data][:images][:fixed_height]
  lib/giphy_client.rb:16:in `translate'
    JSON.parse(resp, symbolize_names: true)[:data][:images][:fixed_height]
  app/models/hackbot/conversations/gifs.rb:16:in `start'
    gif = GiphyClient.translate query
  app/models/hackbot/conversation.rb:28:in `handle'
    next_state = send(state, event)
  app/models/hackbot/conversations/channel.rb:12:in `handle'
    super
...
(143 additional frame(s) were not displayed)

TypeError: no implicit conversion of Symbol into Integer
```

**Comment by MaxWofford** [comment]
Closing this as part of our "Sentry Bankruptcy" -- we've gotten behind on Sentry issues so instead of fixing them retroactively we'll be closing them all and giving any new caught issues top priority.
