### ISSUE TITLE
ArgumentError: Before update callback :update_box_if_changed has not been defined

### ISSUE THREAD

**Issue by zachlatta** [hackclub/api#15]
https://sentry.io/hack-club/api/issues/191055524/

```
ArgumentError: Before update callback :update_box_if_changed has not been defined
  app/models/concerns/streakable.rb:44:in `update_attributes_without_streak'
    self.class.skip_callback(:update, :before, :update_box_if_changed)
  app/jobs/update_from_streak_job.rb:32:in `block (2 levels) in perform'
    instance.update_attributes_without_streak(attrs_to_update)
  app/jobs/update_from_streak_job.rb:20:in `each'
    model_boxes.each do |box|
  app/jobs/update_from_streak_job.rb:20:in `block in perform'
    model_boxes.each do |box|
  app/jobs/update_from_streak_job.rb:15:in `each'
    streakable_models.each do |model|
...
(138 additional frame(s) were not displayed)

ArgumentError: Before update callback :update_box_if_changed has not been defined
```

**Comment by zachlatta** [comment]
Have not been able to reproduce this issue, closing.
