### ISSUE TITLE
NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by zachlatta** [hackclub/api#196]
https://sentry.io/hack-club/api/issues/253005205/

```
NoMethodError: undefined method `[]' for nil:NilClass
  app/models/hackbot/interactions/concerns/mirrorable.rb:21:in `block (2 levels) in <module:Mirrorable>'
    mirror_msg(bot_slack_user, channel, msg[:ts], msg)
  app/models/hackbot/interactions/text_conversation.rb:26:in `msg_channel'
    send_msg(data['channel'], msg)
  app/models/hackbot/interactions/sql.rb:108:in `execute'
    msg_channel to_code(res)
  app/models/hackbot/interactions/sql.rb:98:in `confirm'
    when Hackbot::Utterances.yes then execute
  app/models/hackbot/interaction.rb:33:in `block in handle'
    next_state = send(state)
...
(152 additional frame(s) were not displayed)

NoMethodError: undefined method `[]' for nil:NilClass
```

**Comment by zachlatta** [comment]
This is caused when Hackbot tries to mirror a message that's too large and Slack denies it.

**Comment by zachlatta** [comment]
Submitted #197 to fix this.
