### ISSUE TITLE
RestClient::InternalServerError: 500 Internal Server Error

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/api#227]
https://sentry.io/hack-club/api/issues/259472599/

```
RestClient::InternalServerError: 500 Internal Server Error
  lib/streak_client.rb:56:in `request'
    req.execute.to_s
  lib/streak_client/box.rb:61:in `edit_field'
    StreakClient.request(
  app/models/concerns/streakable.rb:136:in `block in update_all_streak_fields'
    StreakClient::Box.edit_field(
  app/models/concerns/streakable.rb:133:in `each'
    self.class.field_mappings.keys.each do |attribute|
  app/models/concerns/streakable.rb:133:in `update_all_streak_fields'
    self.class.field_mappings.keys.each do |attribute|
...
(195 additional frame(s) were not displayed)

RestClient::InternalServerError: 500 Internal Server Error
```

**Comment by paked** [comment]
This issue hasn't happened in the past 30 days. I think we might have inadvertently fixed it.

**Comment by MaxWofford** [comment]
@paked: Could you resolve it on Sentry?
