### ISSUE TITLE
NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/api#248]
https://sentry.io/hack-club/api/issues/295290025/

```
NoMethodError: undefined method `[]' for nil:NilClass
  app/models/hackbot/interactions/notify.rb:25:in `wait_for_should_send'
    case action[:value]
  app/models/hackbot/interaction.rb:33:in `block in handle'
    next_state = send(state)
  app/models/hackbot/interaction.rb:32:in `handle'
    run_callbacks :handle do
  app/models/hackbot/interactions/text_conversation.rb:20:in `handle'
    super
  app/models/hackbot/dispatcher.rb:49:in `block in run_interaction'
    interaction.handle
...
(149 additional frame(s) were not displayed)

NoMethodError: undefined method `[]' for nil:NilClass
```

**Comment by paked** [comment]
Fixed in #249
