### ISSUE TITLE
Errno::ECONNRESET: Connection reset by peer - SSL_connect

### ISSUE THREAD

**Issue by zachlatta** [hackclub/api#29]
https://sentry.io/hack-club/api/issues/191055350/

```
Errno::ECONNRESET: Connection reset by peer - SSL_connect
  app/models/concerns/streakable.rb:45:in `update_attributes_without_streak'
    update_attributes(attrs)
  app/jobs/update_from_streak_job.rb:32:in `block (2 levels) in perform'
    instance.update_attributes_without_streak(attrs_to_update)
  app/jobs/update_from_streak_job.rb:20:in `each'
    model_boxes.each do |box|
  app/jobs/update_from_streak_job.rb:20:in `block in perform'
    model_boxes.each do |box|
  app/jobs/update_from_streak_job.rb:15:in `each'
    streakable_models.each do |model|
...
(179 additional frame(s) were not displayed)

Errno::ECONNRESET: Connection reset by peer - SSL_connect
```

This should be caught and trigger a retry.

**Comment by MaxWofford** [comment]
Closing this as part of our "Sentry Bankruptcy" -- we've gotten behind on Sentry issues so instead of fixing them retroactively we'll be closing them all and giving any new caught issues top priority.
