### ISSUE TITLE
RestClient::Exceptions::ReadTimeout: Timed out reading data from server (Streak)

### ISSUE THREAD

**Issue by zachlatta** [hackclub/api#30]
https://sentry.io/hack-club/api/issues/189416792/

```
Net::ReadTimeout: Net::ReadTimeout
  lib/streak_client.rb:41:in `request'
    resp = RestClient::Request.execute(method: method, url: api_url(path),
  lib/streak_client/box.rb:37:in `update'
    StreakClient.request(:post, "/v1/boxes/#{box_key}", params)
  app/models/concerns/streakable.rb:109:in `update_streak_box'
    StreakClient::Box.update(
  app/models/concerns/streakable.rb:89:in `create_box'
    update_streak_box
  app/controllers/v1/leaders_controller.rb:9:in `intake'
    if leader.save
...
(106 additional frame(s) were not displayed)

RestClient::Exceptions::ReadTimeout: Timed out reading data from server
  lib/streak_client.rb:41:in `request'
    resp = RestClient::Request.execute(method: method, url: api_url(path),
  lib/streak_client/box.rb:37:in `update'
    StreakClient.request(:post, "/v1/boxes/#{box_key}", params)
  app/models/concerns/streakable.rb:109:in `update_streak_box'
    StreakClient::Box.update(
  app/models/concerns/streakable.rb:89:in `create_box'
    update_streak_box
  app/controllers/v1/leaders_controller.rb:9:in `intake'
    if leader.save
...
(95 additional frame(s) were not displayed)

RestClient::Exceptions::ReadTimeout: Timed out reading data from server
```

Same deal as #29. This should be caught and trigger a retry.

**Comment by MaxWofford** [comment]
https://sentry.io/hack-club/api/issues/217329825/

**Comment by MaxWofford** [comment]
Closing this as part of our "Sentry Bankruptcy" -- we've gotten behind on Sentry issues so instead of fixing them retroactively we'll be closing them all and giving any new caught issues top priority.
