### ISSUE TITLE
RuntimeError: command failed (exitstatus=0): /app/vendor/bundle/ruby/2.3.0/bin/wkhtmltopdf --quiet --page-size ...

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/api#327]
https://sentry.io/hack-club/api/issues/434470733/

```
RuntimeError: command failed (exitstatus=0): /app/vendor/bundle/ruby/2.3.0/bin/wkhtmltopdf --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 "http://:/v1/repo/workshops/collaborative_sketch/README.html?stylesheet=true" -
  app/services/repo_file_service.rb:57:in `pdf'
    kit.to_pdf
  app/services/repo_file_service.rb:26:in `handle'
    return pdf if markdown_as_pdf?
  app/controllers/v1/repo_controller.rb:9:in `file'
    out = file_service.handle
...
(54 additional frame(s) were not displayed)

RuntimeError: command failed (exitstatus=0): /app/vendor/bundle/ruby/2.3.0/bin/wkhtmltopdf --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 "http://:/v1/repo/workshops/collaborative_sketch/README.html?stylesheet=true" -
```

**Comment by lachlanjc** [comment]
Is this still occurring?

**Comment by lachlanjc** [comment]
Re-open if we're still using this
