### ISSUE TITLE
RestClient::Exceptions::ReadTimeout: Timed out reading data from server (Cloud9)

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/api#91]
https://sentry.io/hack-club/api/issues/223859524/

```
Net::ReadTimeout: Net::ReadTimeout
  lib/cloud9_client.rb:35:in `request'
    resp = RestClient::Request.execute(method: method, url: api_url(path),
  lib/cloud9_client/team.rb:22:in `invite_member'
    Cloud9Client.request(:post, "/user/org/#{team_name}/invite", email: email)
  app/controllers/v1/cloud9_controller.rb:22:in `invite_member'
    Cloud9Client::Team.invite_member(
  app/controllers/v1/cloud9_controller.rb:11:in `send_invite'
    invite_member(email)
...
(70 additional frame(s) were not displayed)

RestClient::Exceptions::ReadTimeout: Timed out reading data from server
  lib/cloud9_client.rb:35:in `request'
    resp = RestClient::Request.execute(method: method, url: api_url(path),
  lib/cloud9_client/team.rb:22:in `invite_member'
    Cloud9Client.request(:post, "/user/org/#{team_name}/invite", email: email)
  app/controllers/v1/cloud9_controller.rb:22:in `invite_member'
    Cloud9Client::Team.invite_member(
  app/controllers/v1/cloud9_controller.rb:11:in `send_invite'
    invite_member(email)
...
(59 additional frame(s) were not displayed)

RestClient::Exceptions::ReadTimeout: Timed out reading data from server
```

Same as #30, but in the Cloud9 adapter.

**Comment by MaxWofford** [comment]
Closing this as part of our "Sentry Bankruptcy" -- we've gotten behind on Sentry issues so instead of fixing them retroactively we'll be closing them all and giving any new caught issues top priority.
